# Generated by Django 5.1.2 on 2024-12-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catgory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_catgory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
