# Generated by Django 5.1.2 on 2025-03-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
