# Generated by Django 5.1.2 on 2025-03-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'out for Delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
