# Generated by Django 5.1.2 on 2025-06-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('To be delivered', 'To be delivered'), ('Out for delivery', 'out for Delivery'), ('Delivered', 'Delivered')], default='To be delivered', max_length=200, null=True),
        ),
    ]
